language: php

php:
  - 5.5.9
  - 5.5
  - 5.6
  - 7.0
  - hhvm

sudo: false

services:
  - mysql

before_script:
  - mysql -e 'create database laravel;'
  - export DB_DATABASE=
  - export DB_USERNAME=travis
  - export DB_PASSWORD=
  - php artisan migrate

install:
  - travis_retry composer create-project jadjoubran/laravel5-angular-material-starter=dev-master --no-interaction --prefer-source

script: cd laravel5-angular-material-starter && vendor/bin/phpunit
