language: php

php:
  - 5.5.9
  - 5.5
  - 5.6
  - 7.0
  - hhvm

sudo: false

install:
  - travis_retry composer create-project jadjoubran/laravel5-angular-material-starter --no-interaction --prefer-source

script: ./vendor/bin/phpunit
